apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: go
          artifact-id: bb9a1682-5b6f-4206-a051-d52c93a332c3
          target-environment: PREPROD